### ISSUE TITLE
Tab dataset

### ISSUE THREAD

**Issue by peiherng97** [wayne391/GAN-tutorial#1]
Hi, may i ask where is the tab dataset sourced from? And looking at the proc.py, the x_phr.npy is made up of four consecutive bars? And does x_bar.npy contain only the first bar of the phrase?

**Comment by wayne391** [comment]
Hi, the source of the tab dataset is from [Theorytab](https://www.hooktheory.com/theorytab). You can find the part of crawled data from my another [repo](https://github.com/wayne391/Lead-Sheet-Dataset/tree/master/datasets). However, because the website of Theorytab is updated recently, some errors in crawling or parsing may occur. To get the full version of Theorytab immediately, you can ask 
 and mail to my advisor (yang@citi.sinica.edu.tw) to get permission because it's our lab's resource.

For the later questions, the answers are **Yes**. 'x_phr.npy ' consists of four consecutive bars and ' x_bar.npy'  excerpts only the first bar of each phrase.

**Comment by peiherng97** [comment]
May i know how did you sample those phrases? How many phrases are extracted from one song? And is it transposed to Cmaj?

**Comment by wayne391** [comment]
The phrases are just randomly sampled. The current bottleneck is that there is no reliable 'symbolic music segmentation algorithm' even on the simplest realistic dataset like lead sheets. Without sufficient accuracy, the outcome of any preprocessing step still acts like random. Hence, I tried to keep it simple! However, Theorytab is clean enough so I think you can write your own sample policy based on your purpose. One example is to compute 'phrases per song' according to the desired size of the training data.

Actually, songs from Theorytab are divided into small **sections** due to copyright issues. For each section, it has its **key** such as **C major** or **C dorian**.  I did transpose all sections to **C key** but it could be different modes like 'Major', 'Minor', 'Dorian', 'Phrygian' and etc. I think its the most reasonable way to reduce overhead in learning. 

For more details, I recommend you to check out my another [repo](https://github.com/wayne391/Lead-Sheet-Dataset). I did lots of work there and you could find many interesting things if you go through it.
